spring:
  datasource:
    url: jdbc:mysql://localhost:53306/alarm_it
    username: ryuoo0
    password: rlgus!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /